const constant = {
    USERS: 'Users',
    FETCH_USER: 'FETCH_USER',
    SIGN_UP: 'SIGN_UP',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL',
    LOG_IN_FAIL: 'LOG_IN_FAIL',
    CARDS: 'Cards',
    CREATE_CARD: 'CREATE_CARD',
    UPDATE_CARD: 'UPDATE_CARD',
    FETCH_CARDS: 'FETCH_CARDS',
    TRANSACTIONS: 'Transactions',
    FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
    SEND_OR_REQUEST: 'SEND_OR_REQUEST',
    ACCEPT_REQUEST: 'ACCEPT_REQUEST',
    SET_AMOUNT: 'SET_AMOUNT',
    SET_IS_TENTH: 'SET_IS_TENTH'
}

export default constant;